package br.com.supermidia.calculo.domain;

public enum TipoCalculo {
	AREA_BASE,
	AREA_COM_FATOR,
	AREA_COM_ACRESCIMOS_E_FATOR,
	PERIMETRO_BASE,
	PERIMETRO_COM_ESPACAMENTO,
	UNIDADE_FIXA,
	SELECAO_POR_MEDIDA,
	QUANTIDADE_INFORMADA,
	METRO_LINEAR_INFORMADO
}
