spring.application.name=supermidia
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
#logging.level.org.springframework=DEBUG
#logging.level.br.com.supermidia=DEBUG
#security.jwt.secret-key=${JWT_SECRET_KEY:8Gzxm3baXPRs38XLfswGIhf/3+VMD8w0cgcL0LVIXM0=}
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=432000000
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000
spring.mail.default-encoding=UTF-8
logging.level.org.springframework=INFO
logging.level.root=INFO
server.address=0.0.0.0
server.port=8080
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://192.168.3.10:3000}
app.cors.allowed-methods=${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
app.cors.allowed-headers=${CORS_ALLOWED_HEADERS:*}
app.cors.allow-credentials=${CORS_ALLOW_CREDENTIALS:true}
